[loadbalancers]
load-01 ansible_connection=lxd

[loadbalancers:vars]
ansible_python_interpreter=/usr/bin/python3

[webservers]
server-01 ansible_connection=lxd
server-02 ansible_connection=lxd

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3

[databases]
database-01 ansible_connection=lxd

[databases:vars]
ansible_python_interpreter=/usr/bin/python3


