# Physical host machine.
[lxc_host]
# Host IP address or hostname as well as sshkey
192.168.0.7 ansible_user=spyx ansible_ssh_private_key_file=~/.ssh/lxc/ansible_key.pub

[lxc_host:vars]
# Ensures Ansible can use python3 on host machine
ansible_python_interpreter=/usr/bin/python3

