---
# Template for ansible playbook
- name: Deploy LXC nginx Load-Balanced Stack with PostgreSQL
  hosts: lxc_host
  become: true
  vars:
   container_distro: ubuntu
   container_release: noble #24.04 lts
   #server_distro:
   #server_release:
   
   # Network Configuration
   lxc_gateway: "10.145.169.1"

   db_server: { name: 'database-01', ip: '10.145.169.9' }
   load_balancer: { name: 'load-01', ip: '10.145.169.7' }
   server-_servers:
    - { name: 'server-01', ip: '10.10.1.4' }
    - { name: 'server-02', ip: '10.10.1.5' }

  tasks:
   # Container provisioning
    - name: Create Database Container
      community.general.lxc_container:
       name: "{{ db_server.name }}"
       template: "{{ container_distro }}"
       state: started
       template_options: "--release {{ container_release }}"
       container_config: 
        - "lxc.net.0.ipv4.address = {{ db_server.ip }}/28"
        - "lxc.net.0.ipv4.gateway = {{ lxc_gateway }}"
...
